CREATE DATABASE IF NOT EXISTS encuesta
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE encuesta;

CREATE TABLE IF NOT EXISTS encuesta_linux (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    edad INT NOT NULL,
    sexo ENUM('Masculino', 'Femenino', 'Otro') NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    distro VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO encuesta_linux (nombre_completo, edad, sexo, correo, distro) VALUES
('Juan Pérez', 25, 'Masculino', 'juan.perez@email.com', 'Ubuntu'),
('María González', 32, 'Femenino', 'maria.gonzalez@email.com', 'Fedora'),
('Carlos López', 41, 'Masculino', 'carlos.lopez@email.com', 'Debian'),
('Ana Martínez', 19, 'Femenino', 'ana.martinez@email.com', 'Arch Linux'),
('Luis Rodríguez', 28, 'Masculino', 'luis.rodriguez@email.com', 'Linux Mint'),
('Laura Sánchez', 35, 'Femenino', 'laura.sanchez@email.com', 'openSUSE'),
('Javier Ramírez', 22, 'Masculino', 'javier.ramirez@email.com', 'Pop!_OS'),
('Sofía Torres', 29, 'Femenino', 'sofia.torres@email.com', 'Manjaro'),
('Diego Flores', 45, 'Masculino', 'diego.flores@email.com', 'CentOS'),
('Valentina Rojas', 31, 'Femenino', 'valentina.rojas@email.com', 'Ubuntu'),
('Andrés Morales', 27, 'Masculino', 'andres.morales@email.com', 'Fedora'),
('Camila Ortega', 23, 'Femenino', 'camila.ortega@email.com', 'Debian'),
('Fernando Castro', 38, 'Masculino', 'fernando.castro@email.com', 'Arch Linux'),
('Isabella Gutiérrez', 26, 'Femenino', 'isabella.gutierrez@email.com', 'Linux Mint'),
('Ricardo Ortiz', 33, 'Masculino', 'ricardo.ortiz@email.com', 'openSUSE'),
('Daniela Reyes', 24, 'Femenino', 'daniela.reyes@email.com', 'Pop!_OS'),
('Alejandro Aguilar', 36, 'Masculino', 'alejandro.aguilar@email.com', 'Manjaro'),
('Paula Mendoza', 30, 'Femenino', 'paula.mendoza@email.com', 'CentOS'),
('Sergio Silva', 42, 'Masculino', 'sergio.silva@email.com', 'Ubuntu'),
('Natalia Cruz', 21, 'Femenino', 'natalia.cruz@email.com', 'Fedora'),
('Oscar Romero', 47, 'Masculino', 'oscar.romero@email.com', 'Debian'),
('Gabriela Vargas', 34, 'Femenino', 'gabriela.vargas@email.com', 'Arch Linux'),
('Héctor Delgado', 29, 'Masculino', 'hector.delgado@email.com', 'Linux Mint'),
('Elena Fernández', 39, 'Femenino', 'elena.fernandez@email.com', 'openSUSE'),
('Pablo Jiménez', 31, 'Masculino', 'pablo.jimenez@email.com', 'Pop!_OS'),
('Lucía Herrera', 26, 'Femenino', 'lucia.herrera@email.com', 'Manjaro'),
('Raúl Molina', 44, 'Masculino', 'raul.molina@email.com', 'CentOS'),
('Patricia Vega', 37, 'Femenino', 'patricia.vega@email.com', 'Ubuntu'),
('Alberto Ruiz', 33, 'Masculino', 'alberto.ruiz@email.com', 'Fedora'),
('Mónica Díaz', 28, 'Femenino', 'monica.diaz@email.com', 'Debian'),
('Roberto Peña', 52, 'Masculino', 'roberto.pena@email.com', 'Arch Linux'),
('Adriana Méndez', 27, 'Femenino', 'adriana.mendez@email.com', 'Linux Mint'),
('Manuel Navarro', 35, 'Masculino', 'manuel.navarro@email.com', 'openSUSE'),
('Verónica Luna', 43, 'Femenino', 'veronica.luna@email.com', 'Pop!_OS'),
('Francisco Campos', 24, 'Masculino', 'francisco.campos@email.com', 'Manjaro'),
('Silvia Fuentes', 32, 'Femenino', 'silvia.fuentes@email.com', 'CentOS'),
('Enrique Salazar', 46, 'Masculino', 'enrique.salazar@email.com', 'Ubuntu'),
('Rosa Paredes', 29, 'Femenino', 'rosa.paredes@email.com', 'Fedora'),
('Eduardo Calderón', 38, 'Masculino', 'eduardo.calderon@email.com', 'Debian'),
('Cristina Bautista', 22, 'Femenino', 'cristina.bautista@email.com', 'Arch Linux'),
('Emilio Estrada', 40, 'Masculino', 'emilio.estrada@email.com', 'Linux Mint'),
('Lorena Valenzuela', 34, 'Femenino', 'lorena.valenzuela@email.com', 'openSUSE'),
('Arturo Quintero', 30, 'Masculino', 'arturo.quintero@email.com', 'Pop!_OS'),
('Mariana Zavala', 25, 'Femenino', 'mariana.zavala@email.com', 'Manjaro'),
('Guillermo Maldonado', 49, 'Masculino', 'guillermo.maldonado@email.com', 'CentOS'),
('Claudia Lara', 28, 'Femenino', 'claudia.lara@email.com', 'Ubuntu'),
('Armando Ponce', 36, 'Masculino', 'armando.ponce@email.com', 'Fedora'),
('Diana Espinoza', 31, 'Femenino', 'diana.espinoza@email.com', 'Debian'),
('Mario Rosales', 44, 'Masculino', 'mario.rosales@email.com', 'Arch Linux'),
('Carolina Robles', 27, 'Femenino', 'carolina.robles@email.com', 'Linux Mint'),
('Jorge León', 33, 'Masculino', 'jorge.leon@email.com', 'openSUSE'),
('Teresa Hernández', 41, 'Femenino', 'teresa.hernandez@email.com', 'Pop!_OS'),
('Ramón Gil', 35, 'Masculino', 'ramon.gil@email.com', 'Manjaro'),
('Liliana Cervantes', 29, 'Femenino', 'liliana.cervantes@email.com', 'CentOS'),
('Vicente Padilla', 48, 'Masculino', 'vicente.padilla@email.com', 'Ubuntu'),
('Erika Santos', 26, 'Femenino', 'erika.santos@email.com', 'Fedora'),
('César Acosta', 37, 'Masculino', 'cesar.acosta@email.com', 'Debian'),
('Blanca Núñez', 23, 'Femenino', 'blanca.nunez@email.com', 'Arch Linux'),
('Antonio Villalobos', 50, 'Masculino', 'antonio.villalobos@email.com', 'Linux Mint'),
('Julia Miranda', 32, 'Femenino', 'julia.miranda@email.com', 'openSUSE'),
('René Carrillo', 28, 'Masculino', 'rene.carrillo@email.com', 'Pop!_OS'),
('Gloria Chávez', 39, 'Femenino', 'gloria.chavez@email.com', 'Manjaro'),
('Rubén Santana', 45, 'Masculino', 'ruben.santana@email.com', 'CentOS'),
('Margarita Huerta', 33, 'Femenino', 'margarita.huerta@email.com', 'Ubuntu'),
('Saúl Ramos', 30, 'Masculino', 'saul.ramos@email.com', 'Fedora'),
('Alicia Cabrera', 24, 'Femenino', 'alicia.cabrera@email.com', 'Debian'),
('Gabriel Rangel', 42, 'Masculino', 'gabriel.rangel@email.com', 'Arch Linux'),
('Luz Tapia', 36, 'Femenino', 'luz.tapia@email.com', 'Linux Mint'),
('Moisés Franco', 29, 'Masculino', 'moises.franco@email.com', 'openSUSE'),
('Elisa Cordero', 35, 'Femenino', 'elisa.cordero@email.com', 'Pop!_OS'),
('Felipe Montoya', 47, 'Masculino', 'felipe.montoya@email.com', 'Manjaro'),
('Renata Sosa', 31, 'Femenino', 'renata.sosa@email.com', 'CentOS'),
('Emmanuel Ponce', 38, 'Masculino', 'emmanuel.ponce@email.com', 'Ubuntu'),
('Miriam Guevara', 27, 'Femenino', 'miriam.guevara@email.com', 'Fedora'),
('Agustín Vázquez', 53, 'Masculino', 'agustin.vazquez@email.com', 'Debian'),
('Cecilia Mejía', 34, 'Femenino', 'cecilia.mejia@email.com', 'Arch Linux'),
('Salvador Arriaga', 41, 'Masculino', 'salvador.arriaga@email.com', 'Linux Mint'),
('Esther Castañeda', 26, 'Femenino', 'esther.castaneda@email.com', 'openSUSE'),
('Tomás Vera', 32, 'Masculino', 'tomas.vera@email.com', 'Pop!_OS'),
('Brenda Rentería', 29, 'Femenino', 'brenda.renteria@email.com', 'Manjaro'),
('Ismael Cortés', 44, 'Masculino', 'ismael.cortes@email.com', 'CentOS'),
('Sara Valdés', 37, 'Femenino', 'sara.valdes@email.com', 'Ubuntu'),
('Edgar Luján', 30, 'Masculino', 'edgar.lujan@email.com', 'Fedora'),
('Rocío Solís', 25, 'Femenino', 'rocio.solis@email.com', 'Debian'),
('Nicolás Benavides', 40, 'Masculino', 'nicolas.benavides@email.com', 'Arch Linux'),
('Fabiola Orozco', 33, 'Femenino', 'fabiola.orozco@email.com', 'Linux Mint'),
('Hugo Pineda', 46, 'Masculino', 'hugo.pineda@email.com', 'openSUSE'),
('Julieta Arce', 28, 'Femenino', 'julieta.arce@email.com', 'Pop!_OS'),
('Gerardo Cuevas', 35, 'Masculino', 'gerardo.cuevas@email.com', 'Manjaro'),
('Ivonne Olvera', 31, 'Femenino', 'ivonne.olvera@email.com', 'CentOS'),
('Leonardo Medina', 49, 'Masculino', 'leonardo.medina@email.com', 'Ubuntu'),
('Martha Ibáñez', 27, 'Femenino', 'martha.ibanez@email.com', 'Fedora'),
('Iván Márquez', 39, 'Masculino', 'ivan.marquez@email.com', 'Debian'),
('Leticia Segura', 34, 'Femenino', 'leticia.segura@email.com', 'Arch Linux'),
('Mauricio Llamas', 42, 'Masculino', 'mauricio.llamas@email.com', 'Linux Mint'),
('Karla Fierro', 29, 'Femenino', 'karla.fierro@email.com', 'openSUSE'),
('Ernesto García', 36, 'Masculino', 'ernesto.garcia@email.com', 'Pop!_OS'),
('Adela Bernal', 33, 'Femenino', 'adela.bernal@email.com', 'Manjaro'),
('Octavio Aranda', 45, 'Masculino', 'octavio.aranda@email.com', 'CentOS'),
('Lourdes Toledo', 30, 'Femenino', 'lourdes.toledo@email.com', 'Ubuntu'),
('Fausto Ibarra', 38, 'Masculino', 'fausto.ibarra@email.com', 'Fedora'),
('Abril Ochoa', 26, 'Femenino', 'abril.ochoa@email.com', 'Debian'),
('José Escobar', 48, 'Masculino', 'jose.escobar@email.com', 'Arch Linux'),
('Selena Domínguez', 32, 'Femenino', 'selena.dominguez@email.com', 'Linux Mint'),
('Alan Briseño', 29, 'Masculino', 'alan.briseno@email.com', 'openSUSE'),
('Yolanda Galindo', 41, 'Femenino', 'yolanda.galindo@email.com', 'Pop!_OS'),
('Rodrigo Cisneros', 35, 'Masculino', 'rodrigo.cisneros@email.com', 'Manjaro'),
('Ariadna Corona', 27, 'Femenino', 'ariadna.corona@email.com', 'CentOS'),
('Simón Fonseca', 52, 'Masculino', 'simon.fonseca@email.com', 'Ubuntu'),
('Carla Zúñiga', 33, 'Femenino', 'carla.zuniga@email.com', 'Fedora'),
('Martín Calvo', 39, 'Masculino', 'martin.calvo@email.com', 'Debian'),
('Lidia Juárez', 24, 'Femenino', 'lidia.juarez@email.com', 'Arch Linux'),
('Edmundo Palacios', 47, 'Masculino', 'edmundo.palacios@email.com', 'Linux Mint'),
('Rebeca Monroy', 31, 'Femenino', 'rebeca.monroy@email.com', 'openSUSE'),
('Félix Anaya', 44, 'Masculino', 'felix.anaya@email.com', 'Pop!_OS'),
('Ángela Mata', 28, 'Femenino', 'angela.mata@email.com', 'Manjaro'),
('Rafael Paz', 37, 'Masculino', 'rafael.paz@email.com', 'CentOS'),
('Noemí Salinas', 35, 'Femenino', 'noemi.salinas@email.com', 'Ubuntu'),
('Esteban Barrios', 42, 'Masculino', 'esteban.barrios@email.com', 'Fedora'),
('Amalia Loya', 29, 'Femenino', 'amalia.loya@email.com', 'Debian'),
('Gilberto Carranza', 46, 'Masculino', 'gilberto.carranza@email.com', 'Arch Linux'),
('Pilar Alvarado', 33, 'Femenino', 'pilar.alvarado@email.com', 'Linux Mint'),
('Gustavo Vélez', 38, 'Masculino', 'gustavo.velez@email.com', 'openSUSE'),
('Mayra Quiroz', 27, 'Femenino', 'mayra.quiroz@email.com', 'Pop!_OS'),
('Humberto Becerra', 50, 'Masculino', 'humberto.becerra@email.com', 'Manjaro'),
('Elsa Trujillo', 34, 'Femenino', 'elsa.trujillo@email.com', 'CentOS'),
('Jesús Moreno', 41, 'Masculino', 'jesus.moreno@email.com', 'Ubuntu'),
('Sonia Lozano', 30, 'Femenino', 'sonia.lozano@email.com', 'Fedora'),
('Fabián Alonso', 36, 'Masculino', 'fabian.alonso@email.com', 'Debian'),
('Adrián Macías', 28, 'Masculino', 'adrian.macias@email.com', 'Arch Linux'),
('Bárbara Ferrer', 32, 'Femenino', 'barbara.ferrer@email.com', 'Linux Mint'),
('Darío Gómez', 45, 'Masculino', 'dario.gomez@email.com', 'openSUSE'),
('Imelda Zamora', 39, 'Femenino', 'imelda.zamora@email.com', 'Pop!_OS'),
('Alfonso Esparza', 43, 'Masculino', 'alfonso.esparza@email.com', 'Manjaro'),
('Juana Loera', 26, 'Femenino', 'juana.loera@email.com', 'CentOS'),
('Óscar Amaya', 34, 'Masculino', 'oscar.amaya@email.com', 'Ubuntu'),
('Nora Pedraza', 29, 'Femenino', 'nora.pedraza@email.com', 'Fedora'),
('David Ríos', 48, 'Masculino', 'david.rios@email.com', 'Debian'),
('Dulce Saucedo', 31, 'Femenino', 'dulce.saucedo@email.com', 'Arch Linux'),
('Julián Fajardo', 40, 'Masculino', 'julian.fajardo@email.com', 'Linux Mint'),
('Georgina Olivares', 27, 'Femenino', 'georgina.olivares@email.com', 'openSUSE'),
('Abraham Beltrán', 37, 'Masculino', 'abraham.beltran@email.com', 'Pop!_OS'),
('Catalina Luna', 35, 'Femenino', 'catalina.luna@email.com', 'Manjaro'),
('Rogelio Contreras', 49, 'Masculino', 'rogelio.contreras@email.com', 'CentOS'),
('Mireya Rendón', 28, 'Femenino', 'mireya.rendon@email.com', 'Ubuntu'),
('León Ávalos', 44, 'Masculino', 'leon.avalos@email.com', 'Fedora'),
('Aurora Cárdenas', 33, 'Femenino', 'aurora.cardenas@email.com', 'Debian'),
('Cristóbal Romo', 41, 'Masculino', 'cristobal.romo@email.com', 'Arch Linux'),
('Jacqueline Dávila', 30, 'Femenino', 'jacqueline.davila@email.com', 'Linux Mint'),
('Kevin Vallejo', 26, 'Masculino', 'kevin.vallejo@email.com', 'openSUSE'),
('Tamara Arenas', 38, 'Femenino', 'tamara.arenas@email.com', 'Pop!_OS'),
('Víctor Portillo', 42, 'Masculino', 'victor.portillo@email.com', 'Manjaro'),
('Susana Mojica', 29, 'Femenino', 'susana.mojica@email.com', 'CentOS'),
('Ezequiel Rocha', 35, 'Masculino', 'ezequiel.rocha@email.com', 'Ubuntu'),
('Araceli Cuellar', 32, 'Femenino', 'araceli.cuellar@email.com', 'Fedora'),
('Efraín Godínez', 47, 'Masculino', 'efrain.godinez@email.com', 'Debian'),
('Gisela Peralta', 24, 'Femenino', 'gisela.peralta@email.com', 'Arch Linux'),
('Benito Barragán', 39, 'Masculino', 'benito.barragan@email.com', 'Linux Mint'),
('Leticia Arredondo', 36, 'Femenino', 'leticia.arredondo2@email.com', 'openSUSE'),
('Renato Uribe', 41, 'Masculino', 'renato.uribe@email.com', 'Pop!_OS'),
('Magdalena Paniagua', 28, 'Femenino', 'magdalena.paniagua@email.com', 'Manjaro'),
('Bruno Zaragoza', 33, 'Masculino', 'bruno.zaragoza@email.com', 'CentOS'),
('Verónica Gómez', 35, 'Femenino', 'veronica.gomez2@email.com', 'Ubuntu'),
('Mauro Rodríguez', 46, 'Masculino', 'mauro.rodriguez@email.com', 'Fedora'),
('Selene Lara', 29, 'Femenino', 'selene.lara@email.com', 'Debian'),
('Eugenio Ponce', 38, 'Masculino', 'eugenio.ponce@email.com', 'Arch Linux'),
('Ximena Castro', 27, 'Femenino', 'ximena.castro@email.com', 'Linux Mint');
